[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  PUBLIC_GISCUS_REPO_ID = "R_kgDOTYsYvQ"
  PUBLIC_GISCUS_CATEGORY_ID = "DIC_kwDOTYsYvc4DBOds"
